Use Git Sparse checkout to make it easier to get the local rules
oxc-project/eslint-plugin-oxlint pull request #64
Opened 2024-04-25 14:11 UTC by vincentbriglia

Making these changes is a prerequisite to get the categories of each of the rules according to this request: https://github.com/oxc-project/eslint-plugin-oxlint/issues/61 which makes sense to then create recommended configurations for the separate configs. 

opening this PR is to get input on direction and if this is agreed on.

2024-04-29 09:22 UTC, vincentbriglia commented
@Boshen @Djiit feedback requested if you want to go down this way

2024-04-29 09:49 UTC, Dunqing commented
Thank you for your working on this! Although this will become quite complex, doing so is meaningful, go ahead!

2024-04-30 07:49 UTC, vincentbriglia commented
this will now print out this config: 

```
{
  configs: {
    recommended: {
      plugins: [ 'oxlint' ],
      rules: {
        'for-direction': 'off',
        'no-async-promise-executor': 'off',
        'no-caller': 'off',
        'no-class-assign': 'off',
        'no-compare-neg-zero': 'off',
        'no-cond-assign': 'off',
        'no-const-assign': 'off',
        'no-constant-binary-expression': 'off',
        'no-constant-condition': 'off',
        'no-control-regex': 'off',
        'no-debugger': 'off',
        'no-delete-var': 'off',
        'no-dupe-class-members': 'off',
        'no-dupe-else-if': 'off',
        'no-dupe-keys': 'off',
        'no-duplicate-case': 'off',
        'no-empty-character-class': 'off',
        'no-empty-pattern': 'off',
        'no-empty-static-block': 'off',
        'no-ex-assign': 'off',
        'no-extra-boolean-cast': 'off',
        'no-func-assign': 'off',
        'no-global-assign': 'off',
        'no-inner-declarations': 'off',
        'no-irregular-whitespace': 'off',
        'no-loss-of-precision': 'off',
        'no-new-symbol': 'off',
        'no-nonoctal-decimal-escape': 'off',
        'no-obj-calls': 'off',
        'no-self-assign': 'off',
        'no-setter-return': 'off',
        'no-shadow-restricted-names': 'off',
        'no-sparse-arrays': 'off',
        'no-this-before-super': 'off',
        'no-unsafe-finally': 'off',
        'no-unsafe-negation': 'off',
        'no-unused-labels': 'off',
        'no-unused-private-class-members': 'off',
        'no-useless-catch': 'off',
        'no-useless-escape': 'off',
        'no-useless-rename': 'off',
        'no-with': 'off',
        'require-yield': 'off',
        'use-isnan': 'off',
        'valid-typeof': 'off',
        'jest/expect-expect': 'off',
        'jest/no-conditional-expect': 'off',
        'jest/no-disabled-tests': 'off',
        'jest/no-export': 'off',
        'jest/no-focused-tests': 'off',
        'jest/no-standalone-expect': 'off',
        'jest/require-to-throw-message': 'off',
        'jest/valid-describe-callback': 'off',
        'jest/valid-expect': 'off',
        'jest/valid-title': 'off',
        'jsdoc/check-property-names': 'off',
        'jsdoc/require-property': 'off',
        'jsdoc/require-property-description': 'off',
        'jsdoc/require-property-name': 'off',
        'jsdoc/require-property-type': 'off',
        'jsx-a11y/alt-text': 'off',
        'jsx-a11y/anchor-has-content': 'off',
        'jsx-a11y/anchor-is-valid': 'off',
        'jsx-a11y/aria-activedescendant-has-tabindex': 'off',
        'jsx-a11y/aria-props': 'off',
        'jsx-a11y/aria-role': 'off',
        'jsx-a11y/aria-unsupported-elements': 'off',
        'jsx-a11y/autocomplete-valid': 'off',
        'jsx-a11y/click-events-have-key-events': 'off',
        'jsx-a11y/heading-has-content': 'off',
        'jsx-a11y/html-has-lang': 'off',
        'jsx-a11y/iframe-has-title': 'off',
        'jsx-a11y/img-redundant-alt': 'off',
        'jsx-a11y/lang': 'off',
        'jsx-a11y/media-has-caption': 'off',
        'jsx-a11y/mouse-events-have-key-events': 'off',
        'jsx-a11y/no-access-key': 'off',
        'jsx-a11y/no-aria-hidden-on-focusable': 'off',
        'jsx-a11y/no-autofocus': 'off',
        'jsx-a11y/no-distracting-elements': 'off',
        'jsx-a11y/no-redundant-roles': 'off',
        'jsx-a11y/prefer-tag-over-role': 'off',
        'jsx-a11y/role-has-required-aria-props': 'off',
        'jsx-a11y/role-supports-aria-props': 'off',
        'jsx-a11y/scope': 'off',
        'jsx-a11y/tabindex-no-positive': 'off',
        'nextjs/google-font-display': 'off',
        'nextjs/google-font-preconnect': 'off',
        'nextjs/inline-script-id': 'off',
        'nextjs/next-script-for-ga': 'off',
        'nextjs/no-assign-module-variable': 'off',
        'nextjs/no-async-client-component': 'off',
        'nextjs/no-before-interactive-script-outside-document': 'off',
        'nextjs/no-css-tags': 'off',
        'nextjs/no-document-import-in-page': 'off',
        'nextjs/no-head-element': 'off',
        'nextjs/no-head-import-in-document': 'off',
        'nextjs/no-img-element': 'off',
        'nextjs/no-script-component-in-head': 'off',
        'nextjs/no-sync-scripts': 'off',
        'nextjs/no-title-in-document-head': 'off',
        'nextjs/no-typos': 'off',
        'nextjs/no-unwanted-polyfillio': 'off',
        'react/jsx-key': 'off',
        'react/jsx-no-duplicate-props': 'off',
        'react/jsx-no-target-blank': 'off',
        'react/jsx-no-undef': 'off',
        'react/jsx-no-useless-fragment': 'off',
        'react/no-children-prop': 'off',
        'react/no-direct-mutation-state': 'off',
        'react/no-find-dom-node': 'off',
        'react/no-is-mounted': 'off',
        'react/no-render-return-value': 'off',
        'react/no-string-refs': 'off',
        'react/require-render-return': 'off',
        'react/void-dom-elements-no-children': 'off',
        'react-perf/jsx-no-jsx-as-prop': 'off',
        'react-perf/jsx-no-new-array-as-prop': 'off',
        'react-perf/jsx-no-new-function-as-prop': 'off',
        'react-perf/jsx-no-new-object-as-prop': 'off',
        '@typescript-eslint/no-extra-non-null-assertion': 'off',
        '@typescript-eslint/no-misused-new': 'off',
        '@typescript-eslint/no-namespace': 'off',
        '@typescript-eslint/no-non-null-asserted-optional-chain': 'off',
        '@typescript-eslint/no-this-alias': 'off',
        '@typescript-eslint/no-unsafe-declaration-merging': 'off',
        '@typescript-eslint/prefer-as-const': 'off',
        '@typescript-eslint/triple-slash-reference': 'off',
        'unicorn/no-await-in-promise-methods': 'off',
        'unicorn/no-document-cookie': 'off',
        'unicorn/no-empty-file': 'off',
        'unicorn/no-invalid-remove-event-listener': 'off',
        'unicorn/no-new-array': 'off',
        'unicorn/no-single-promise-in-promise-methods': 'off',
        'unicorn/no-thenable': 'off',
        'unicorn/no-unnecessary-await': 'off',
        'unicorn/no-useless-fallback-in-spread': 'off',
        'unicorn/no-useless-length-check': 'off',
        'unicorn/no-useless-spread': 'off',
        'unicorn/prefer-set-size': 'off',
        'unicorn/prefer-string-starts-ends-with': 'off'
      }
    },
    'flat/recommended': {
      rules: {
        'for-direction': 'off',
        'no-async-promise-executor': 'off',
        'no-caller': 'off',
        'no-class-assign': 'off',
        'no-compare-neg-zero': 'off',
        'no-cond-assign': 'off',
        'no-const-assign': 'off',
        'no-constant-binary-expression': 'off',
        'no-constant-condition': 'off',
        'no-control-regex': 'off',
        'no-debugger': 'off',
        'no-delete-var': 'off',
        'no-dupe-class-members': 'off',
        'no-dupe-else-if': 'off',
        'no-dupe-keys': 'off',
        'no-duplicate-case': 'off',
        'no-empty-character-class': 'off',
        'no-empty-pattern': 'off',
        'no-empty-static-block': 'off',
        'no-ex-assign': 'off',
        'no-extra-boolean-cast': 'off',
        'no-func-assign': 'off',
        'no-global-assign': 'off',
        'no-inner-declarations': 'off',
        'no-irregular-whitespace': 'off',
        'no-loss-of-precision': 'off',
        'no-new-symbol': 'off',
        'no-nonoctal-decimal-escape': 'off',
        'no-obj-calls': 'off',
        'no-self-assign': 'off',
        'no-setter-return': 'off',
        'no-shadow-restricted-names': 'off',
        'no-sparse-arrays': 'off',
        'no-this-before-super': 'off',
        'no-unsafe-finally': 'off',
        'no-unsafe-negation': 'off',
        'no-unused-labels': 'off',
        'no-unused-private-class-members': 'off',
        'no-useless-catch': 'off',
        'no-useless-escape': 'off',
        'no-useless-rename': 'off',
        'no-with': 'off',
        'require-yield': 'off',
        'use-isnan': 'off',
        'valid-typeof': 'off',
        'jest/expect-expect': 'off',
        'jest/no-condi [...]

2024-04-30 08:44 UTC, Dunqing commented
> I think we should avoid having a non-flat for all the other ones, and instead recommend to use the non-recommended configs together with setting up the plugin manually, otherwise this list will grow.

Yes, I agree

2024-05-01 06:14 UTC, vincentbriglia commented
vitest fsometimes ails because of an upstream issue with the `v8-to-istanbul` library as they have an off-by-one issue

this line is the cause: https://github.com/istanbuljs/v8-to-istanbul/blob/master/lib/range.js#L30 so i would recommend that this coverage reporter be turned off.. 

other than that, this PR is now ready

2024-05-01 06:15 UTC, vincentbriglia commented
I've also fixed so that the codebase works using prettier, and formats the files in vscode when saving. if you don't like the prettier configuration, please recommend what you'd prefer (see `prettier.config.js`)

2024-05-08 08:43 UTC, Dunqing commented on scripts/__snapshots__/rules-generator.test.ts.snap
> +  "/Users/dkVinBri/Development/eslint-plugin-oxlint/src/rules-by-category.ts": "// These rules are automatically generated by scripts/generate-rules.ts
This path only exists in your machine.

2024-05-08 08:47 UTC, Dunqing commented
> vitest sometimes ails because of an upstream issue with the `v8-to-istanbul` library as they have an off-by-one issue
> 
> this line is the cause: https://github.com/istanbuljs/v8-to-istanbul/blob/master/lib/range.js#L30 so i would recommend that this coverage reporter be turned off..
> 

Yes, we can turn off coverage. we don't need it.

2024-05-08 08:59 UTC, Dunqing commented on README.md
> +    'flat/treeShaking': { rules: [Object] },
I think here we should use kebab-case.

2024-05-08 09:00 UTC, Dunqing requested changes

2024-05-08 09:00 UTC, Dunqing commented on README.md
> +sparse clone the oxclint repository to have a local copy
```suggestion
sparse clone the oxlint repository to have a local copy
```

2024-05-20 08:58 UTC, Dunqing approved these changes

2024-05-20 08:59 UTC, Dunqing commented
Thanks for working on this! It's amazing for `oxlint` users.

2024-05-20 08:59 UTC, merged